//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Import_Zamowien_Producenckich
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CDNXL_MAGEntities : DbContext
    {
        public CDNXL_MAGEntities()
            : base("name=CDNXL_MAGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MAG_ZamProdNag> MAG_ZamProdNag { get; set; }
        public virtual DbSet<MAG_ZamProdPoz> MAG_ZamProdPoz { get; set; }
        public virtual DbSet<MAG_EBIZAM_Konfig> MAG_EBIZAM_Konfig { get; set; }
    }
}
