//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Import_Zamowien_Producenckich
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAG_ZamProdNag
    {
        public int Zpn_ID { get; set; }
        public string Zpn_nazwa_pliku { get; set; }
        public string Zpn_Sciezka { get; set; }
        public string Zpn_Producent { get; set; }
        public Nullable<int> Zpn_Status { get; set; }
        public Nullable<bool> Zpn_Alert { get; set; }
        public Nullable<bool> Zpn_AlertKnt { get; set; }
        public Nullable<int> Zpn_KntXL { get; set; }
        public string Zpn_ZRODLO_CEL { get; set; }
        public string Zpn_ID_MAG { get; set; }
        public string Zpn_NR_ZAM { get; set; }
        public string Zpn_ID_PRAC { get; set; }
        public string Zpn_NAZWISKO { get; set; }
        public string Zpn_IMIE { get; set; }
        public string Zpn_ID_KLT { get; set; }
        public string Zpn_NAZWA { get; set; }
        public string Zpn_MIASTO { get; set; }
        public string Zpn_ULICA { get; set; }
        public string Zpn_NR_LOK { get; set; }
        public string Zpn_NIP { get; set; }
        public string Zpn_TYP_ZAM { get; set; }
        public Nullable<System.DateTime> Zpn_DATA_ZAM { get; set; }
        public Nullable<System.DateTime> Zpn_DATA_DOST { get; set; }
        public Nullable<decimal> Zpn_RABAT_ZAM { get; set; }
        public string Zpn_UWAGI { get; set; }
        public Nullable<int> Zpn_WSK_PRM { get; set; }
        public Nullable<int> Zpn_ID_PRM_EBI { get; set; }
        public string Zpn_NAZWA_PRM { get; set; }
        public Nullable<int> Zpn_EmailSent { get; set; }
        public Nullable<System.DateTime> Zpn_DataPliku { get; set; }
    }
}
