//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Import_Zamowien_Producenckich
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAG_ZamProdPoz
    {
        public int Zpp_ID { get; set; }
        public int Zpp_zpnid { get; set; }
        public Nullable<bool> Zpp_AlertTwr { get; set; }
        public Nullable<int> Zpp_TwrGIDXL { get; set; }
        public Nullable<int> Zpp_NR_POZ { get; set; }
        public string Zpp_ID_ASO { get; set; }
        public string Zpp_EAN { get; set; }
        public string Zpp_NAZWA { get; set; }
        public Nullable<decimal> Zpp_ILOSC_SZT { get; set; }
        public Nullable<decimal> Zpp_ILOSC { get; set; }
        public string Zpp_ID_JED { get; set; }
        public Nullable<decimal> Zpp_ILOSC_NZ { get; set; }
        public Nullable<System.DateTime> Zpp_DATA_NZ { get; set; }
        public Nullable<decimal> Zpp_CENA_NETTO { get; set; }
        public Nullable<decimal> Zpp_CENA_NETTO_RABAT { get; set; }
        public Nullable<decimal> Zpp_RABAT { get; set; }
        public Nullable<int> Zpp_UKRYJ_RABAT { get; set; }
        public Nullable<int> Zpp_WSK_GRATIS { get; set; }
        public Nullable<int> Zpp_WSK_PRM { get; set; }
        public Nullable<int> Zpp_ID_PRM_EBI { get; set; }
        public Nullable<int> Zpp_ID_PRM_DYS { get; set; }
        public Nullable<int> Zpp_XLZanNumer { get; set; }
        public Nullable<int> Zpp_XLZanTyp { get; set; }
        public Nullable<int> Zpp_XLZanLp { get; set; }
    }
}
