//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Import_Zamowien_Producenckich
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAG_EBIZAM_Konfig
    {
        public int EZam_ID { get; set; }
        public string EZam_ProdAkr { get; set; }
        public string EZam_ProdNazwa { get; set; }
        public bool EZam_Archiwalny { get; set; }
        public string EZam_FoldZrd { get; set; }
        public string EZam_FoldDoc { get; set; }
        public string EZam_FoldArch { get; set; }
        public Nullable<bool> EZam_GenPlikDoc { get; set; }
        public string EZam_PlikZrdRozsz { get; set; }
        public string EZam_PlikZrdFormat { get; set; }
    }
}
